import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navbar';
import WhatsAppButton from '@/components/whatsapp-button';

const manrope = Manrope({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-manrope',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={manrope.variable}>
      <body className={`antialiased`}>
        <Navbar />
        <div className="mt-24 lg:mt-36 xl:mt-48">{children}</div>
        <WhatsAppButton />
      </body>
    </html>
  );
}
