import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navbar';

const manrope = Manrope({
  subsets: ['latin'],
  // Optional: you can specify weight
  // weight: ['400', '500', '700'],
  // Optional: you can specify style
  // style: ['normal', 'italic'],
  display: 'swap',
  variable: '--font-manrope',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={manrope.variable}>
      <body className={`antialiased`}>
        <Navbar />
        <div className="mt-48">{children}</div>
      </body>
    </html>
  );
}
